services:
  - type: web
    name: barber
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: BARBER_DATABASE_URL
        sync: false
